### PR TITLE
Added a new field ('cover') to the user record

### PR DESCRIPTION
**Pull request by fycth**
This field could contain an URL to the profile user's cover image (Facebook, Twtter, etc.). I made also an appropriate change into AVZ to get this URL during login/registration process.

### CODE REVIEW

**Comment by 5HT** [comment]
The avatar field exactly for that purposes.

**Comment by skatt** [comment]
In Facebook, avatar and cover are two different images. Would we store a tuple list to hold both under the avatar variable?

**Comment by 5HT** [comment]
Yes probably we should rename `avatar` field to field `images` like `tokens` field for handling proplist of tokens [{facebook,Token},{twitter,Token},{email,Token},{n2o,Token}], e.g: [{avatar,Avatar},{cover,Cover}]

**Comment by skatt** [comment]
Thank you. That sounds great.

**Comment by 5HT** [comment]
Check This Out:
https://github.com/synrc/kvs/commit/83b8cadbac41116748354fb62c32734a01e60815

**Pull request closed without merging**
